version: "3"
services:

  web:
    image: ebm1718travis/redline:latest
    # depends_on:
    #   - mongodb
    environment:
      - MONGODB_URI=mongodb://mongodb/redline
      - APP_PORT=4000
    networks:
      local:
      ebm-filrouge:
        aliases:
          - redline
  # mongodb:
  #   image: mongo
  #   networks:
  #     - local
networks:
  local:
  ebm-filrouge:
    external: true
